_wandb:
    value:
        cli_version: 0.21.0
        e:
            tyv9jdp2oq2txxymhrz5ju7w5k74hmh3:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                codePath: jax-dqn.py
                codePathLocal: jax-dqn.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "242715013120"
                email: jackbmontgomery2001@gmail.com
                executable: /Users/jackmontgomery/personal/workspace/.venv/bin/python3
                git:
                    commit: ed4dce2655ea1062bfad4d5480b65e76cd87d08b
                    remote: https://github.com/jackbmontgomery/workspace.git
                host: MacBookPro.lan
                memory:
                    total: "17179869184"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/jackmontgomery/personal/workspace/jax-dqn.py
                python: CPython 3.12.9
                root: /Users/jackmontgomery/personal/workspace
                startedAt: "2025-07-17T12:43:40.640853Z"
                writerId: tyv9jdp2oq2txxymhrz5ju7w5k74hmh3
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 12
                - 45
            "2":
                - 12
                - 45
            "3":
                - 2
            "4": 3.12.9
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
